uploads = []
outputs = []

[[generated]]
id = "n4SXsZ-4UmeSfqI_z2ehi"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "dlvNXl8gWw7ep7b3vZSsV"
uri = "file://artifacts/mobile/assets/images/splash.png"
type = "image"
title = "generated_image"
